### ISSUE TITLE
Image extraction problem

### ISSUE THREAD

**Issue by ilanb** [imanoop7/Generative-Search-Engine-For-Local-Files-v2#1]
Hello, 

I get error for each image extracted :

`Starting the application...
Initialized model and FAISS index with dimension 768
Starting Streamlit UI
Loading FAISS index and metadata
Application finished
2024-10-24 23:28:25.259 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
Starting the application...
Initialized model and FAISS index with dimension 768
Starting Streamlit UI
Indexing documents in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data
Indexing documents in directory: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data
Processing file: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Duval-PantagruelsGenealogyRedemptive-1984fr.pdf
Reading PDF: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Duval-PantagruelsGenealogyRedemptive-1984fr.pdf
Chunking text of length 102469 with chunk size 500 and overlap 50
Created 35 chunks
Processing image
Processing image
Processing image
Processing image
Processing file: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/GoffartVisionsubmitted.pdf
Reading PDF: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/GoffartVisionsubmitted.pdf
Chunking text of length 161144 with chunk size 500 and overlap 50
Created 55 chunks
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing file: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Astrobioethicsfr.pdf
Reading PDF: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Astrobioethicsfr.pdf
Chunking text of length 40677 with chunk size 500 and overlap 50
Created 13 chunks
Processing image
Processing file: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/articlescientifiqueIlan.pdf
Reading PDF: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/articlescientifiqueIlan.pdf
Chunking text of length 94517 with chunk size 500 and overlap 50
Created 34 chunks
Processing image
Processing image
Processing file: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf
Reading PDF: /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf
Chunking text of length 63371 with chunk size 500 and overlap 50
Created 22 chunks
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Processing image
Encoding 186 document chunks and images
2024-10-24 23:28:35.518 Uncaught app exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/labop9/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/miniconda3/envs/labop9/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/ilan/_INFOSTRATES/_AI/LaboP9/local_genai_search.py", line 477, in <module>
    main()
  File "/Users/ilan/_INFOSTRATES/_AI/LaboP9/local_genai_search.py", line 388, in main
    index_documents(documents_path)
  File "/Users/ilan/_INFOSTRATES/_AI/LaboP9/local_genai_search.py", line 164, in index_documents
    image_description = llava_generate("Describe this image in detail.", doc)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilan/_INFOSTRATES/_AI/LaboP9/local_genai_search.py", line 294, in llava_generate
    base64_image = encode_image_to_base64(image_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ilan/_INFOSTRATES/_AI/LaboP9/local_genai_search.py", line 289, in encode_image_to_base64
    with open(image_path, "rb") as image_file:
         ^^^^^^^^^^^^^^^^^^^^^^
ValueError: embedded null byte
2024-10-24 23:28:35.602 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_`

Any clue ?

Thanks you

**Comment by ilanb** [comment]
I tried a simple test to verify my pdf and all works fine 

`import os
import fitz  # PyMuPDF for PDF image extraction
from PIL import Image
import io
import base64

def extract_images_from_pdf(file_path):
    images = []
    # Open the PDF file
    doc = fitz.open(file_path)
    try:
        for page_num in range(len(doc)):
            page = doc.load_page(page_num)
            # Retrieve list of images stored in the page
            image_list = page.get_images(full=True)
            for img_index, img in enumerate(image_list):
                xref = img[0]
                # Extract the image metadata using xref index
                base_image = doc.extract_image(xref)
                # Get the image bytes
                image_bytes = base_image["image"]
                # Create an image object and add to the list
                image = Image.open(io.BytesIO(image_bytes))
                images.append((file_path, page_num + 1, img_index, image))
    finally:
        # Ensure the document is closed to free resources
        doc.close()
    return images

def encode_image_to_base64(image):
    buffered = io.BytesIO()
    image.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')
    return img_str

pdf_path = "/Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf"
images = extract_images_from_pdf(pdf_path)

if images:
    for file_path, page_num, img_index, image in images:
        print(f"Found image in {file_path}, Page: {page_num}, Index: {img_index}")
        
        # Encode the image to base64
        base64_image = encode_image_to_base64(image)
        print(f"Base64 encoded image for page {page_num} and index {img_index}: {base64_image[:100]}... (truncated)")
else:
    print("No images found in the PDF.")`
    
    
    (labop9) ilan@macbook-pro LaboP9 % python app.py
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 1, Index: 0
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 1, Index: 1
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 2, Index: 0
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 3, Index: 0
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 4, Index: 0
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 5, Index: 0
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 6, Index: 0
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 6, Index: 1
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 7, Index: 0
(labop9) ilan@macbook-pro LaboP9 % python app.py
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 1, Index: 0
Base64 encoded image for page 1 and index 0: iVBORw0KGgoAAAANSUhEUgAAAPgAAAEPCAIAAADgU55JAAEAAElEQVR4nJz9d1yTadc1gN4pkEYCSQihJpTQe++C9KZS7IrYu87o... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 1, Index: 1
Base64 encoded image for page 1 and index 1: iVBORw0KGgoAAAANSUhEUgAAAOwAAAEqCAIAAACZdyteAAEAAElEQVR4nOy9d5xkV3Un/j03vPcqdHWcnhwVRjmgjBBIQuRkwLIx... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 2, Index: 0
Base64 encoded image for page 2 and index 0: iVBORw0KGgoAAAANSUhEUgAABkAAAAPQCAIAAADhMCAUAAEAAElEQVR4nOz9d7wt11UljI4511oV9t4n3Xyvrq5yzpZly3JExhEB... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 3, Index: 0
Base64 encoded image for page 3 and index 0: iVBORw0KGgoAAAANSUhEUgAAB2wAAATMCAIAAADEbODkAAEAAElEQVR4nOx9d7wU1fn385yZ2XJ3b+8XuHSQJh1RQBQsKPZg76lG... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 4, Index: 0
Base64 encoded image for page 4 and index 0: iVBORw0KGgoAAAANSUhEUgAABtYAAAd5CAIAAADn2byPAAEAAElEQVR4nOzdd5wb13Uo/nOnomMBbO+Vy7bsvYukCkk1Ky6SbNmS... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 5, Index: 0
Base64 encoded image for page 5 and index 0: iVBORw0KGgoAAAANSUhEUgAAB6EAAAmOCAIAAABqaq9SAAEAAElEQVR4nOzdd5gc1Zk2/OeESh0nz2iSpNFIM8o5SygihAiSyCAw... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 6, Index: 0
Base64 encoded image for page 6 and index 0: iVBORw0KGgoAAAANSUhEUgAABqQAAAP4CAIAAAA0xgpEAAEAAElEQVR4nOzdd3hc130n/HPO7dMrBr33Xth7l0RRvVdbrkmcxClv... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 6, Index: 1
Base64 encoded image for page 6 and index 1: iVBORw0KGgoAAAANSUhEUgAACBsAAALmCAIAAACG5pmpAAEAAElEQVR4nOz9d5icx3knilb4Yufp7ulJmBnkQSIJgCTABCZRFKlE... (truncated)
Found image in /Users/ilan/_INFOSTRATES/_AI/LaboP9/data/Tombinsetal2024.pdf, Page: 7, Index: 0
Base64 encoded image for page 7 and index 0: iVBORw0KGgoAAAANSUhEUgAACBsAAASyCAIAAAByKeZyAAEAAElEQVR4nOz9Z5RkR5YeCN57zewJd4+IVAASqExorYEqlIKsQomu... (truncated)

**Comment by imanoop7** [comment]
there's an embedded null byte in the image_path, which is causing the open function to fail.
have added fix for this, hope it will work for you
